In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [3]:
import torch.nn as nn

inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

# need to convert to the tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

weight = torch.rand((3,1))*10

print(weight)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
tensor([[5.5041],
        [0.3867],
        [2.0136]])


In [8]:
# create the dataset
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets)
# ":" means all the row , ":n" => display only n rows
print(dataset[:3])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.],
        [ 81.],
        [119.]]))


In [9]:
# creating dataloader of specific batch size
from torch.utils.data import DataLoader

batch_size = 5
train_loader = DataLoader(dataset, batch_size = batch_size, shuffle = True)

In [10]:
# access the dataloader
for inp, target in train_loader:
  print(inp)
  print(target)
  break

tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.]])
tensor([[103.],
        [119.],
        [ 56.],
        [ 81.],
        [ 22.]])


In [15]:
weights = torch.randn(1,3, requires_grad=True)
bias = torch.randn(1, requires_grad = True)
print(weights)
print(bias)

tensor([[ 0.4469, -0.2256,  0.8093]], requires_grad=True)
tensor([0.9563], requires_grad=True)


In [19]:
# defining the model
def model(X):
  return X @ weights.t() + bias

for x,y in train_loader:
  preds = model(x)
  print("Predictions is :n", preds)
  print("Actual targets is :n", y)
  break

Predictions is :n tensor([[73.5607],
        [53.2599],
        [66.7779],
        [56.5381],
        [66.7808]], grad_fn=<AddBackward0>)
Actual targets is :n tensor([[ 81.],
        [ 56.],
        [ 22.],
        [119.],
        [103.]])


In [23]:
# MSE loss function
def mse_loss(predictions, targets):
  difference = predictions - targets
  print(difference.numel())
  return torch.sum(difference * difference)/difference.numel()

for x,y in train_loader:
  pred = model(x)
  print("Prediction is :n",preds)
  print("nActual targets is :\n",y)
  print("nLoss is: ",mse_loss(preds, y))
  break

Prediction is :n tensor([[73.5607],
        [53.2599],
        [66.7779],
        [56.5381],
        [66.7808]], grad_fn=<AddBackward0>)
nActual targets is :
 tensor([[119.],
        [103.],
        [ 81.],
        [ 22.],
        [ 56.]])
5
nLoss is:  tensor(1210.0381, grad_fn=<DivBackward0>)


In [24]:
# gradient descent algorithm
epochs = 50
for i in range(epochs):
    # Iterate through training dataloader
    for x,y in train_loader:
        # Generate Prediction
        preds = model(x)
        # Get the loss and perform backpropagation
        loss = mse_loss(preds, y)
        loss.backward()
        # Let's update the weights
        with torch.no_grad():
            weights -= weights.grad *1e-6
            bias -= bias.grad * 1e-6
            # Set the gradients to zero
            weights.grad.zero_()
            bias.grad.zero_()
    print(f"Epoch {i}/{epochs}: Loss: {loss}")

5
Epoch 0/50: Loss: 1456.2457275390625
5
Epoch 1/50: Loss: 1431.0953369140625
5
Epoch 2/50: Loss: 1407.5203857421875
5
Epoch 3/50: Loss: 1385.410400390625
5
Epoch 4/50: Loss: 1364.6627197265625
5
Epoch 5/50: Loss: 1345.1820068359375
5
Epoch 6/50: Loss: 1326.879638671875
5
Epoch 7/50: Loss: 1309.673095703125
5
Epoch 8/50: Loss: 1293.486328125
5
Epoch 9/50: Loss: 1278.2474365234375
5
Epoch 10/50: Loss: 1263.890380859375
5
Epoch 11/50: Loss: 1250.353759765625
5
Epoch 12/50: Loss: 1237.580078125
5
Epoch 13/50: Loss: 1225.5162353515625
5
Epoch 14/50: Loss: 1214.1129150390625
5
Epoch 15/50: Loss: 1203.323974609375
5
Epoch 16/50: Loss: 1193.106689453125
5
Epoch 17/50: Loss: 1183.421142578125
5
Epoch 18/50: Loss: 1174.2310791015625
5
Epoch 19/50: Loss: 1165.5013427734375
5
Epoch 20/50: Loss: 1157.2000732421875
5
Epoch 21/50: Loss: 1149.298095703125
5
Epoch 22/50: Loss: 1141.767333984375
5
Epoch 23/50: Loss: 1134.5823974609375
5
Epoch 24/50: Loss: 1127.71923828125
5
Epoch 25/50: Loss: 1121.1560

In [25]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :n",preds)
    print("nActual targets is :n",y)
    break

Prediction is :n tensor([[77.4117],
        [64.6312],
        [74.9914],
        [88.8292],
        [83.1998]], grad_fn=<AddBackward0>)
nActual targets is :n tensor([[119.],
        [ 56.],
        [ 22.],
        [ 81.],
        [103.]])


In [ ]:
model = np.dot(inputs, weight)
print(model)

randNum = torch.rand(1)*10
print(randNum)

for i in range(0,5):
    model[i][0] += randNum

print(model)

[[ 818.16144]
 [1072.8108 ]
 [1439.8029 ]
 [ 684.12366]
 [1090.8981 ]]
tensor([2.7404])
[[ 820.90186]
 [1075.5511 ]
 [1442.5432 ]
 [ 686.8641 ]
 [1093.6384 ]]


1.1 Linear Regression Model using PyTorch built-ins

In [ ]:
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

dataset = TensorDataset(inputs, targets)
print(dataset)

loader = DataLoader(dataset, batch_size=2,pin_memory=True)
print(loader)

1.1.2 nn.Linear

In [ ]:
model = torch.nn.Linear(2,3)
print(model)

Linear(in_features=2, out_features=3, bias=True)


1.1.3 Optimizer

In [ ]:
params = model.parameters()
print(params)



<generator object Module.parameters at 0x7f7efd1056d0>


In [ ]:
from torch import optim

opt = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
print(opt)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)


1.1.4 Loss Function

In [ ]:
# Import nn.functional
import torch.nn.functional as F

In [ ]:
# Define loss function
loss_fn = F.mse_loss
print(loss_fn)

<function mse_loss at 0x7f7eff056b80>


In [ ]:
loss = loss_fn(inputs, targets)
print(loss)

tensor(1023.1334)


<ipython-input-38-6068755b0614>:1: UserWarning: Using a target size (torch.Size([5, 1])) that is different to the input size (torch.Size([5, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = loss_fn(inputs, targets)


In [ ]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      # Generate predictions
      pred = model()
      loss = loss_fn(inputs, targets)
      # Perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
  print('Training loss: ', loss_fn(model(inputs), targets))

RuntimeError: ignored

In [ ]:
fit(datasets, model, loss_fn, opt)